app = "leveraged-fund-trading"

[build]
  dockerfile = "Dockerfile"

[env]
  ALPACA_PAPER_API_KEY = "your_api_key"
  ALPACA_PAPER_API_SECRET = "your_api_secret"

[[services]]
  internal_port = 8000
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
  [services.http_checks]
    path = "/"
    port = 80
    grace_period = "5s"
    interval = "15s"
    retries = 3
    timeout = "2s"
