name: Build & Release Lambda Layer

on:
  push:
    # branches:
    #   - main
    paths:
      - 'layer/**'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upgrade pip, setuptools & wheel       # <-- Insert upgrade here
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies into layer
        run: |
          pip install \
            --target layer/python/lib/python3.11/site-packages \
            -r layer/requirements.txt

      - name: Zip the layer directory
        run: |
          cd layer
          zip -r ../layer.zip python

      - name: Upload layer artifact
        uses: actions/upload-artifact@v3
        with:
          name: python3-11-layer
          path: layer.zip

      - name: Publish to AWS Lambda Layer
        id: publish-layer
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          LAYER_ARN=$(aws lambda publish-layer-version \
            --layer-name my-python3-11-deps \
            --description "Dependencies for Python 3.11" \
            --zip-file fileb://layer.zip \
            --compatible-runtimes python3.11 \
            --query 'LayerVersionArn' \
            --output text)
          echo "::set-output name=layer_arn::$LAYER_ARN"

      - name: Attach Layer to Lambda Function
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws lambda update-function-configuration \
            --function-name MyFunction \
            --layers ${{ steps.publish-layer.outputs.layer_arn }}
