name: Build & Deploy Weekly Deposit Lambda

on:
  push:
    paths:
      - 'lambda_bot_weekly_deposit/**'
      - '.github/workflows/deploy-weekly-deposit.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      WEEKLY_DEPOSIT_FUNCTION_NAME: ${{ secrets.WEEKLY_DEPOSIT_FUNCTION_NAME }}
      LAYER_BUCKET:                ${{ secrets.LAYER_S3_BUCKET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: Set up Python 3.11.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.9'

      # ─── Layer: weekly-deposit-deps (alpaca-py) ─────────────────────────────
      - name: Install weekly-deposit-deps layer dependencies (Amazon Linux 2)
        run: |
          python -m pip install --upgrade pip
          mkdir -p layer/python

          docker run --rm \
            -v "${{ github.workspace }}/layer/python":/opt/python \
            public.ecr.aws/sam/build-python3.11:latest \
            /bin/bash -c "
              pip install --no-cache-dir \
                alpaca-py \
                -t /opt/python \
              && find /opt/python -name '*.dist-info' -or -name '*.egg-info' | xargs rm -rf
            "

      - name: Package weekly-deposit-deps layer
        run: |
          cd layer
          zip -r ../weekly_deposit_layer.zip python

      - name: Upload weekly deposit layer.zip to S3
        run: aws s3 cp weekly_deposit_layer.zip s3://$LAYER_BUCKET/weekly_deposit_layer.zip

      - name: Publish new weekly-deposit-deps Lambda layer version
        id: publish_weekly_deposit_layer
        run: |
          LAYER_ARN=$(aws lambda publish-layer-version \
            --layer-name weekly-deposit-deps \
            --description "Dependencies for weekly deposit bot (alpaca-py)" \
            --license-info "MIT" \
            --content S3Bucket=$LAYER_BUCKET,S3Key=weekly_deposit_layer.zip \
            --compatible-runtimes python3.11 \
            --output text \
            --query LayerVersionArn)
          echo "weeklyDepositLayerArn=$LAYER_ARN" >> $GITHUB_OUTPUT

      - name: Show published Weekly Deposit Layer ARN
        run: echo "→ ${{ steps.publish_weekly_deposit_layer.outputs.weeklyDepositLayerArn }}"

      # ─── Weekly Deposit Lambda packaging & deploy ─────────────────────────────
      - name: Package Weekly Deposit Lambda function code
        run: zip -r weekly_deposit_function.zip lambda_bot_weekly_deposit common

      - name: Update Weekly Deposit Lambda function code
        run: |
          aws lambda update-function-code \
            --function-name $WEEKLY_DEPOSIT_FUNCTION_NAME \
            --zip-file fileb://weekly_deposit_function.zip

      - name: Wait for Weekly Deposit function to be Active
        run: aws lambda wait function-active --function-name $WEEKLY_DEPOSIT_FUNCTION_NAME

      - name: Attach Weekly Deposit Layer & handler to Lambda (with retry)
        run: |
          LAYER_ARN=${{ steps.publish_weekly_deposit_layer.outputs.weeklyDepositLayerArn }}
          for i in {1..6}; do
            echo "Attempt $i to update Weekly Deposit Lambda configuration..."
            if aws lambda update-function-configuration \
                 --function-name $WEEKLY_DEPOSIT_FUNCTION_NAME \
                 --handler lambda_bot_weekly_deposit.lambda_function.make_weekly_deposit \
                 --layers "$LAYER_ARN"; then
              echo "✔ Weekly Deposit Lambda config updated."
              break
            else
              echo "⚠️ Conflict updating Weekly Deposit Lambda—retrying in 10s..."
              sleep 10
            fi
          done
